### ISSUE TITLE
Write the MDC0 FCL file

### ISSUE THREAD

**Issue by lyon-fnal** [lyon-my-gm2/mergeathon#10]
Need to write the MDC0 fcl file. 

Options we need:
* Run Nathan's beam dynamics gas gun `GasGunBdyn`
* Make Cherenkov tracks in the calorimeter crystals with the lookup table 
* Use CADMesh geometries
* Write out random number engine state

**Comment by lyon-fnal** [comment]
Created `gm2ringsim/fcl/mdc0.fcl`

**Comment by lyon-fnal** [comment]
With `mdc0.fcl` I'm getting stuck tracks (sometimes many) on nearly every event. Investigating...

**Comment by lyon-fnal** [comment]
From Leah...

> Some initial findings from this mega-stuck tracks issue that Adam was seeing. 

> When I used the mdc0.fcl file as is, but commented out all the detectors but the VacuumChamberCadMesh I saw what adam saw with tons of stuck tracks on a large percentage of events, with some having multiple stuck tracks. Weird obviously, because there is the only one detector in there...what is it getting stuck on?

> I tried using the gas gun that was in the cadMeshVac.fcl file (G2PGA) and then I only had one event (out of 100) with a stuck track (and it was only stuck for 10 steps, not for multiple times in the same event). The next time I tried it I saw three events. So obviously we still have stuck tracks....BUT not at the same level. 
> So I don't know the difference between the new gas gun and the old one, but this could be where the problem lies. I haven't tried it with all the objects back in, but we should get it working with just the vacuum chamber and then we should be able to add the other things back in.

**Comment by leahcwr** [comment]
Having more information on the the difference between the two gas guns (G2PGA and GasGunBdyn) as it looks like this is what caused so many differences. But again we wanted to leave the stuck tracks alone until we got the new GEANT. Could the older version of GEANT and the New gas gun be causing more problems then the old GEANT and the old gas gun?

**Comment by lyon-fnal** [comment]
But why would the new Gas gun make this big a difference? Unless the e+ is always appearing within a tessellated volume. Looking...

**Comment by lyon-fnal** [comment]
Adding @rfatemi

**Comment by lyon-fnal** [comment]
Trying with the Gaussian Gas gun for comparison... I see a very large number of stuck tracks with the Gaussian Gas gun too. That is...

![image](https://cloud.githubusercontent.com/assets/9458395/12572447/3d6ee0a2-c3b2-11e5-9d80-60bcbb02f52a.png)

**Comment by lyon-fnal** [comment]
Trying the old gas gun...

![image](https://cloud.githubusercontent.com/assets/9458395/12572556/b264efea-c3b3-11e5-9921-f235af368a04.png)

Also lots of stuck tracks

**Comment by lyon-fnal** [comment]
Trying to reproduce what Leah saw - using the Gas gun in `cadMeshVac.fcl`...

![image](https://cloud.githubusercontent.com/assets/9458395/12572588/fa600d84-c3b3-11e5-8eaf-660b889ded69.png)

Now I see the stuck tracks at the few percent level!

**Comment by leahcwr** [comment]
Glad we see the same thing! So we need more details on the differences in the guns.

**Comment by lyon-fnal** [comment]
So `G2PGA`, which `cadMeshVac.fcl` is using, is not a gas gun. It's the original `g2migtrace` gun that shoots muons from a particular place (in this case defined by `G2GPS_downstreamInflectorMandrel_muplus` in `g2GPS.fcl`). The exact location, energy, time, and direction wiggle around according to distributions, but basically the muons all come from the same place (`pos_centre: [ 7149.62, 0, -751.455 ] //mm`). So I think this explains why we see very different behavior between this and the gas guns. Will try to make some visualizations to confirm. But I think we should just go ahead with the beam dynamics gas gun and suffer through the stuck tracks. Hopefully Geant 10.2 will do something good.

**Comment by lyon-fnal** [comment]
Looking at the run of `cadMeshVac.fcl` with the `G2GPA` gun and 200 events overlaid, indeed you see the muons starting from about the same place...


This picture shows the start of the muon tracks (bluer is more at the beginning of the track). 200 events are overlaid. 
![image](https://cloud.githubusercontent.com/assets/9458395/12575053/2087b956-c3cf-11e5-81cb-1ae9008c68eb.png)


Same events with the ring
![image](https://cloud.githubusercontent.com/assets/9458395/12575043/0a7ec6fe-c3cf-11e5-8a35-5ccac2a9ee9e.png)

![image](https://cloud.githubusercontent.com/assets/9458395/12575031/e1e36a60-c3ce-11e5-976f-5cf0fae9e23d.png)

**Comment by lyon-fnal** [comment]
I'm trying to make a similar picture for the `mdc0.fcl` output (with the beam dynamics gas gun), but there are hundreds of tracks per event, and so ParaView is *really* slow. So here's a little movie of playing through events. You see they start in different places (and they're lots of tracks!). 

![fast](https://cloud.githubusercontent.com/assets/9458395/12589946/05dc6c62-c426-11e5-96fd-30eaab21336c.gif)

**Comment by lyon-fnal** [comment]
So there are two conclusions here...

* Continue ahead even with the stuck tracks. 
* Perhaps add a stepping action to kill the enormous number of low energy tracks.
